POST https://nodejs-rocketseat-7law.onrender.com/videos
content-type: application/json

//REQUEST BODY
{
    "title": "First Video 01",
    "description": "This is the first video",
    "duration": 180
}

###

GET https://nodejs-rocketseat-7law.onrender.com/videos

###

// QUERY PARAMETERS / SEARCH PARAMETERS
GET https://nodejs-rocketseat-7law.onrender.com/videos?search=first

###

//ROUTE PARAMETERS
PUT https://nodejs-rocketseat-7law.onrender.com/videos/72f64a6a-ed4d-45cd-a1cd-78b1a8f25627
Content-Type: application/json

{
    "title": "Video 02",
    "description": "This is the second video",
    "duration": 240
}

###

DELETE https://nodejs-rocketseat-7law.onrender.com/videos/72f64a6a-ed4d-45cd-a1cd-78b1a8f25627