POST http://localhost:3333/videos
content-type: application/json

//REQUEST BODY
{
    "title": "First Video 01",
    "description": "This is the first video",
    "duration": 180
}

###

GET http://localhost:3333/videos

###

// QUERY PARAMETERS / SEARCH PARAMETERS
GET http://localhost:3333/videos?search=first

###

//ROUTE PARAMETERS
PUT http://localhost:3333/videos/55140c3f-8013-464d-a6f5-a98dda660640
Content-Type: application/json

{
    "title": "Video 02",
    "description": "This is the second video",
    "duration": 240
}

###

DELETE http://localhost:3333/videos/55140c3f-8013-464d-a6f5-a98dda660640